import type {Metadata} from 'next';
import Link from 'next/link';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';

export const metadata: Metadata = {
  title: 'Firebase Studio App',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet" />
      </head>
      <body className="font-body antialiased">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex flex-col h-screen overflow-hidden">
            <header className="bg-slate-900 text-white px-6 py-3 flex gap-8 items-center shrink-0 z-50">
              <div className="font-bold text-lg tracking-tight">Oceanus RAG</div>
              <nav className="flex gap-6 text-sm font-medium text-slate-300">
                <Link href="/" className="hover:text-white transition-colors">Home</Link>
                <Link href="/graph" className="hover:text-white transition-colors">Graph Explorer</Link>
                <Link href="/search" className="hover:text-white transition-colors">Cycle Search</Link>
              </nav>
            </header>
            <main className="flex-1 overflow-hidden relative">
              {children}
            </main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
